# Site settings
title: stut-it Martin Stut
email: kontakt4711@stut-it.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.stut-it.net" # the base hostname & protocol for your site
port: 4001
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      